services:
    app:
        build:
            context: <Path_to_folder>
            args:
                DB_ENGINE: sqlite
                PRISMA_URL: 'file:<Path_to_file>'
                BETTER_AUTH_URL: 'http://localhost:3000'
                NEXT_PUBLIC_API_URL: 'http://localhost:3000'
        environment:
            DB_ENGINE: sqlite
            PRISMA_URL: 'file:<Path_to_file>'
            BETTER_AUTH_URL: 'http://localhost:3000'
            NEXT_PUBLIC_API_URL: 'http://localhost:3000'
        ports:
            - '3000:3000'
